# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Shapiro Shonda
tagline:          'We made'
description:      'Personally condemned by the board of trustees.'
url:              http://0.0.0.0:4000
baseurl:          /

author:
  name:           'Eden Zik'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/edenzik/ShapiroShonda
